# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  #config.vm.box = "centos6.5"
  #config.vm.box_url = "https://github.com/2creatives/vagrant-centos/releases/download/v6.5.1/centos65-x86_64-20131205.box"

  config.vm.box = "HDP2.1TechPreview"
  config.vm.box_url = "http://dev2.hortonworks.com.s3.amazonaws.com/sandbox/vagrant/HDP2.1TechPreview.box"
  config.vm.box_download_checksum = "89c0555abb50d37d64475d7df96b77e4191c4ae2e5d1531b8545a4aaf5e29ccd"
  config.vm.box_download_checksum_type = "sha256"

  # config.vm.box_check_update = false
  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"

  # If true, then any SSH connections made will enable agent forwarding.
  # Default value: false
  # config.ssh.forward_agent = true

  config.vm.synced_folder "../components", "/components"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.customize ["modifyvm", :id, "--memory", "4096"]
  end


  config.vm.network :forwarded_port, guest: 80, host: 42080, host_ip: "0.0.0.0", auto_correct: true #Apache http
  config.vm.network :forwarded_port, guest: 111, host: 42111, host_ip: "0.0.0.0", auto_correct: true #NFS portmap
  config.vm.network :forwarded_port, guest: 8000, host: 8000, host_ip: "0.0.0.0", auto_correct: true #Hue
  config.vm.network :forwarded_port, guest: 8020, host: 8020, host_ip: "0.0.0.0", auto_correct: true #Hdfs
  config.vm.network :forwarded_port, guest: 8042, host: 8042, host_ip: "0.0.0.0", auto_correct: true #NodeManager
  config.vm.network :forwarded_port, guest: 8050, host: 8050, host_ip: "0.0.0.0", auto_correct: true #Resource manager
  config.vm.network :forwarded_port, guest: 8080, host: 8080, host_ip: "0.0.0.0", auto_correct: true #Ambari
  config.vm.network :forwarded_port, guest: 8088, host: 8088, host_ip: "0.0.0.0", auto_correct: true #Yarn RM
  config.vm.network :forwarded_port, guest: 8443, host: 8443, host_ip: "0.0.0.0", auto_correct: true #Knox gateway
  config.vm.network :forwarded_port, guest: 8744, host: 8744, host_ip: "0.0.0.0", auto_correct: true #Storm UI
  config.vm.network :forwarded_port, guest: 8888, host: 8888, host_ip: "0.0.0.0", auto_correct: true #Tutorials
  config.vm.network :forwarded_port, guest: 10000, host: 10000, host_ip: "0.0.0.0", auto_correct: true #HiveServer2 thrift
  config.vm.network :forwarded_port, guest: 10001, host: 10001, host_ip: "0.0.0.0", auto_correct: true #HiveServer2 thrift http
  config.vm.network :forwarded_port, guest: 11000, host: 11000, host_ip: "0.0.0.0", auto_correct: true #Oozie
  config.vm.network :forwarded_port, guest: 15000, host: 15000, host_ip: "0.0.0.0", auto_correct: true #Falcon
  config.vm.network :forwarded_port, guest: 19888, host: 19888, host_ip: "0.0.0.0", auto_correct: true #Job history
  config.vm.network :forwarded_port, guest: 50070, host: 50070, host_ip: "0.0.0.0", auto_correct: true #WebHdfs
  config.vm.network :forwarded_port, guest: 50075, host: 50075, host_ip: "0.0.0.0", auto_correct: true #Datanode
  config.vm.network :forwarded_port, guest: 50111, host: 50111, host_ip: "0.0.0.0", auto_correct: true #WebHcat
  config.vm.network :forwarded_port, guest: 60080, host: 60080, host_ip: "0.0.0.0", auto_correct: true #WebHBase


  # config.vm.provision "shell", path: "prepare.sh"
end
